# circle.yml #
# machine:
#   go:
#     version: 1.9.1

version: 2

jobs:
  build:
    docker:
      - image: golang:1.14.4
    working_directory: /gopath/src/github.com/vcaesar/tcpp
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: apt-get update
      - run: apt-get -y install libpcap-dev
      # 
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      # codecov.io
      # - run: go test -v -covermode=count -coverprofile=coverage.out
      # - run: bash <(curl -s https://codecov.io/bash)

# script:
#   - ./go.test.sh
